obj-y = main.o syscall.o strace.o mmap.o signal.o \
	elfload.o linuxload.o uaccess.o uname.o \
	safe-syscall.o snapshot.o provenance.o osprey.o osprey-facts.o osprey-rules.o \
	osprey-infer.o osprey-decode.o osprey-relations.o sem-events.o \
	$(TARGET_ABI_DIR)/signal.o \
        $(TARGET_ABI_DIR)/cpu_loop.o exit.o fd-trans.o \
				sbsv.o sbsv_parser.o

obj-$(TARGET_HAS_BFLT) += flatload.o
obj-$(TARGET_I386) += vm86.o
obj-$(TARGET_ARM) += arm/nwfpe/
obj-$(TARGET_ARM) += arm/semihost.o
obj-$(TARGET_AARCH64) += arm/semihost.o
