/* t37: lock-prefixed RMW must not be corrupted by memcheck instrumentation.
 *
 * Regression for the atomic-corruption P0: memcheck_instrument_tb reused a
 * freed-but-still-referenced guest temp (the qemu_st value temp of the
 * non-atomic RMW sequence generated by do_nonatomic_op_i64) for its
 * helper-arg movi, clobbering the stored value.  A single `lock xorq $1`
 * on a global must leave the slot holding exactly 1.
 */
#include <stdint.h>

static volatile uint64_t slot = 0;

int main(void) {
    __asm__ volatile("lock xorq $1, %0" : "+m"(slot));
    if (slot != 1) {
        return 21; /* corrupted: instrumentation clobbered the store value */
    }
    return 0;
}
